// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    print(defaultTargetPlatform);
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      // throw UnsupportedError(
      //   'DefaultFirebaseOptions have not been configured for windows - '
      //   'you can reconfigure this by running the FlutterFire CLI again.',
      // );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjMEXTPSwvfbWG1hZtbEfAgrn_1CLX2pk',
    appId: '1:678518042574:web:115fe43ff1dec8262e459f',
    messagingSenderId: '678518042574',
    projectId: 'brainschildapps',
    authDomain: 'brainschildapps.firebaseapp.com',
    storageBucket: 'brainschildapps.appspot.com',
    measurementId: 'G-SK6FP5T0KC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTMJX1iP7YwJjx-wYs8d8Bi3KyRo7ASN8',
    appId: '1:678518042574:android:05e1d38904bc39262e459f',
    messagingSenderId: '678518042574',
    projectId: 'brainschildapps',
    storageBucket: 'brainschildapps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGg9BC4PcZ3x8I-YdJw_WasiJj5Sj_4KA',
    appId: '1:678518042574:ios:b6ba4fa87657fff02e459f',
    messagingSenderId: '678518042574',
    projectId: 'brainschildapps',
    storageBucket: 'brainschildapps.appspot.com',
    androidClientId:
        '678518042574-cijamkrvejmhu1e4vsr6685f54km1t5s.apps.googleusercontent.com',
    iosClientId:
        '678518042574-qgofc9m6r03kst20ijkqqm55u3sq6mjr.apps.googleusercontent.com',
    iosBundleId: 'com.brainschild.wssprtcl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGg9BC4PcZ3x8I-YdJw_WasiJj5Sj_4KA',
    appId: '1:678518042574:ios:b6ba4fa87657fff02e459f',
    messagingSenderId: '678518042574',
    projectId: 'brainschildapps',
    storageBucket: 'brainschildapps.appspot.com',
    androidClientId:
        '678518042574-cijamkrvejmhu1e4vsr6685f54km1t5s.apps.googleusercontent.com',
    iosClientId:
        '678518042574-qgofc9m6r03kst20ijkqqm55u3sq6mjr.apps.googleusercontent.com',
    iosBundleId: 'com.brainschild.wssprtcl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyAjMEXTPSwvfbWG1hZtbEfAgrn_1CLX2pk",
    authDomain: "brainschildapps.firebaseapp.com",
    projectId: "brainschildapps",
    storageBucket: "brainschildapps.appspot.com",
    messagingSenderId: "678518042574",
    appId: "1:678518042574:web:6944d6da7702b9322e459f",
    measurementId: "G-0RL97D75DV",
  );
}
