// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUNsfXEqlIUL9RayXSSUp19fw30X4cWbI',
    appId: '1:194506996471:web:fb142d8859af53d76bb1f2',
    messagingSenderId: '194506996471',
    projectId: 'brainschildcreations',
    authDomain: 'brainschildcreations.firebaseapp.com',
    storageBucket: 'brainschildcreations.appspot.com',
    measurementId: 'G-9G4Q2B7JGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4tFcuKPc6WQAQa7gzL2wcOS6ztlI-jOk',
    appId: '1:194506996471:android:e202c15147776ecd6bb1f2',
    messagingSenderId: '194506996471',
    projectId: 'brainschildcreations',
    storageBucket: 'brainschildcreations.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUFquZfm5zRTGbS-32GDno0FHdGMVR6zg',
    appId: '1:194506996471:ios:1a4f1f2a0e15071e6bb1f2',
    messagingSenderId: '194506996471',
    projectId: 'brainschildcreations',
    storageBucket: 'brainschildcreations.appspot.com',
    iosClientId: '194506996471-idg8qit6a5q6h9dh6bhgmto7pf0dtmlj.apps.googleusercontent.com',
    iosBundleId: 'com.brainschild.wssprtcl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUFquZfm5zRTGbS-32GDno0FHdGMVR6zg',
    appId: '1:194506996471:ios:1a4f1f2a0e15071e6bb1f2',
    messagingSenderId: '194506996471',
    projectId: 'brainschildcreations',
    storageBucket: 'brainschildcreations.appspot.com',
    iosClientId: '194506996471-idg8qit6a5q6h9dh6bhgmto7pf0dtmlj.apps.googleusercontent.com',
    iosBundleId: 'com.brainschild.wssprtcl',
  );
}
